name: Undertaker

on:
  push:
    tags:
      - "*"
jobs:
  undertaker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      # TODO: There should be an undertaker github action
      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get install -y yq
      - name: Run Undertaker
        run: ./undertaker github.com:undertaker-ci/howto-github-monorepo.git#ci
